Repository scratchfoundation/scratch-vm, pull requests merged in 2018-07, with the labels that each got.

#1212 execute optimization by unwrapping recursion
  src/engine/blocks.js
  src/engine/execute.js
  src/engine/sequencer.js
  src/engine/thread.js
  test/unit/engine_thread.js
Labels: pr - good to merge

#1286 Update package-lock.json
  package-lock.json
Labels: pr - good to merge

#1280 Fix a few say bubble issues
  src/blocks/scratch3_looks.js
Labels: pr - good to merge

#1303 Add implementation for "When loudness >" block
  src/blocks/scratch3_event.js
  test/unit/blocks_event.js
Labels: pr - good to merge

#1301 Variable scope
  src/engine/blocks.js
  src/engine/runtime.js
  src/engine/target.js
  src/engine/variable.js
  src/virtual-machine.js
Labels: pr - good to merge

#1305 Fix tick yielding threads
  src/engine/sequencer.js
Labels: pr - good to merge

#1300 EV3 Extension fixes
  src/extensions/scratch3_ev3/index.js
Labels: pr - good to merge

#1311 Update text-to-speech extension to use new audio engine
  src/extension-support/extension-manager.js
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1319 Remove webpack config from npm ignore.
  .npmignore
Labels: pr - good to merge

#1325 Update microbit block and menu icons using the new ones
  src/extensions/scratch3_microbit/index.js
Labels: pr - needs work

#1318 Set internal connected flag before emitting event
  src/io/bleSession.js
  src/io/btSession.js
Labels: pr - needs review

#1321 Issue/1299 switch language
  src/extension-support/extension-manager.js
  src/virtual-machine.js
Labels: localization, pr - good to merge

#1314 Add micro:bit matrix field block
  src/engine/runtime.js
  src/extension-support/argument-type.js
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1331 Microbit display commands yield for a tick
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1315 Break out loadVector and loadBitmap from loadCostumeAsset, and handle bitmap resolution 1 assets in loadBitmap
  src/engine/runtime.js
  src/import/load-costume.js
  src/virtual-machine.js
Labels: pr - good to merge

#1330 Always glow threads that come from stack clicks
  src/engine/runtime.js
Labels: pr - good to merge

#1333 Change extension name to micro:bit
  src/extensions/scratch3_microbit/index.js
Labels: pr - needs review

#1332 Microbit write bails out if not connected
  src/extensions/scratch3_microbit/index.js
Labels: pr - needs review

#1316 Change translate extension reporter block text to 'language'
  src/extensions/scratch3_translate/index.js
Labels: pr - needs review

#1342 EV3 port and sensor polling updates
  src/extensions/scratch3_ev3/index.js
  src/io/bleSession.js
  src/io/btSession.js
Labels: pr - good to merge

#1224 Turn speech block text into i18n messages.
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1232 Make the end listening sound only play one time even if multiple bloc…
  src/extensions/scratch3_speech/index.js
Labels: pr - needs review

#1346 Use 2x png for microbit icon
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1347 Fix local var rename/delete
  src/engine/blocks.js
Labels: pr - good to merge

#1359 Use secure web socket address for ble and bt connection
  src/io/bleSession.js
  src/io/btSession.js
Labels: pr - needs review

#1354 EV3/Microbit critical fixes for code freeze
  src/engine/runtime.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/io/bleSession.js
  src/io/btSession.js
  src/virtual-machine.js
Labels: pr - good to merge

#1355 Ignore display command with blank string
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1356 Fix microbit display matrix clear function
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1362 Fix duplicating sounds not working
  src/sprites/sprite.js
Labels: pr - good to merge

#1361 Fix sprite upload variable conflict
  src/engine/target.js
  test/unit/engine_target.js
Labels: pr - good to merge

#1341 fix unnecessary stackClick report from nested promise reporters
  src/engine/execute.js
Labels: pr - needs review

#1368 Change 'video motion' to 'video sensing'. See LLK/scratch-gui#2621
  src/extensions/scratch3_video_sensing/index.js
Labels: pr - good to merge

#1367 Add function to return the current VM/blocks locale
  src/virtual-machine.js
Labels: localization, pr - good to merge

#1377 Update the category info name when the extension is refreshed.
  src/engine/runtime.js
Labels: localization, pr - good to merge

#1378 Use the newer date format for vm versions, to get greenkeeper working
  .travis.yml
Labels: pr - good to merge

#1381 Do not send coast if another motor command has been sent
  src/extensions/scratch3_ev3/index.js
Labels: pr - needs review

#1297 Remove some audio config safari can't handle.
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1388 Use sprite’s soundbank to play text2speech sound
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1391 Target ordering
  src/serialization/sb2.js
  test/fixtures/ordering.sb2
  test/unit/serialization_sb2.js
Labels: pr - good to merge

#1383 Feature/critical extension fixes
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/io/bleSession.js
  src/io/btSession.js
Labels: pr - good to merge

#1392 Sprite Layer Ordering Save/Load
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  src/util/math-util.js
  test/fixtures/fake-renderer.js
  test/unit/serialization_sb3.js
  test/unit/sprites_rendered-target.js
  test/unit/util_math.js
Labels: pr - good to merge

#1387 Add UserData ioDevice for setting and getting username from blocks
  src/blocks/scratch3_sensing.js
  src/engine/runtime.js
  src/io/userData.js
  test/unit/blocks_sensing.js
  test/unit/io_userData.js
Labels: pr - good to merge

#1393 Don't serialize layerOrder when exporting a sprite.
  src/serialization/sb3.js
Labels: pr - good to merge

#1399 Add an extra param for adding sounds and costumes to specific targets
  src/virtual-machine.js
Labels: pr - good to merge

#1400 Add "set voice" block to text2speech extension
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge
