Repository scratchfoundation/scratch-vm, pull requests merged in 2018-02, with the labels that each got.

#931 Renaming sprite/costume/sound/backdrop updates corresponding blocks.
  src/engine/blocks.js
  src/sprites/rendered-target.js
  src/virtual-machine.js
  test/unit/engine_blocks.js
  test/unit/virtual-machine.js
Labels: needs-qa, pr - good to merge

#933 When getting sprite by name, skip the stage
  src/engine/runtime.js
Labels: pr - needs review

#936 Feature/require music assets
  package.json
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_music/manifest.js
  webpack.config.js
Labels: pr - good to merge

#920 Scroll wheel detection for "when key (up/down) pressed" blocks
  src/engine/runtime.js
  src/io/mouseWheel.js
  test/unit/io_mousewheel.js
Labels: pr - good to merge

#944 Duplicate costume
  src/sprites/rendered-target.js
  src/virtual-machine.js
Labels: pr - needs review

#939 Block drag
  src/engine/adapter.js
  src/engine/blocks.js
  src/engine/runtime.js
  src/virtual-machine.js
Labels: pr - good to merge

#878 Optimize stepThread by reducing the number of calls to peekStack
  src/engine/sequencer.js
Labels: pr - good to merge

#952 Duplicating sprite should give new sprite a fresh name.
  src/sprites/sprite.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#950 Fix music extension menu import
  src/extensions/scratch3_music/index.js
  src/serialization/sb2.js
  src/serialization/sb2_specmap.js
Labels: pr - good to merge
