Repository scratchfoundation/scratch-vm, pull requests merged in 2018-03, with the labels that each got.

#953 Load tempo from sb2
  src/extensions/scratch3_music/index.js
  src/serialization/sb2.js
  src/sprites/rendered-target.js
  test/unit/extension_music.js
Labels: pr - good to merge

#943 Make sprite.costumes private
  src/blocks/scratch3_looks.js
  src/blocks/scratch3_sensing.js
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/unit/blocks_looks.js
  test/unit/sprites_rendered-target.js
Labels: pr - good to merge

#956 Validate sb2
  package.json
  src/virtual-machine.js
Labels: pr - good to merge

#934 Extensions dynamic menu
  src/engine/runtime.js
  src/extension-support/extension-manager.js
  test/integration/internal-extension.js
Labels: pr - good to merge

#957 Use flag to selectively activate 'when this sprite clicked' hat on mouse up
  src/io/mouse.js
Labels: pr - good to merge

#964 Preliminary Save and Load Work
  package.json
  src/serialization/deserialize-assets.js
  src/serialization/sb3.js
  src/serialization/serialize-assets.js
  src/virtual-machine.js
Labels: pr - needs review

#969 Ensure music extension _decodeSound is promise
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#968 ensure this.workerClass exists before instanceof check
  src/dispatch/central-dispatch.js
Labels: pr - good to merge

#945 Translate extension block
  src/extensions/scratch3_translate/index.js
Labels: pr - needs review

#965 fixed issue 960
  src/blocks/scratch3_looks.js
Labels: pr - needs review

#978 Fix say/think and wait
  src/blocks/scratch3_looks.js
  src/engine/sequencer.js
  test/fixtures/saythink-and-wait.sb2
  test/integration/saythink-and-wait.js
Labels: pr - needs review

#975 Move volume to rendered target
  src/blocks/scratch3_sensing.js
  src/blocks/scratch3_sound.js
  src/sprites/rendered-target.js
Labels: pr - good to merge

#991 Clones share their parent’s activeSoundPlayers object
  src/sprites/rendered-target.js
Labels: pr - good to merge

#994 Looks extension support
  src/extension-support/argument-type.js
  src/extension-support/block-type.js
  src/extension-support/extension-manager.js
  src/extension-support/extension-metadata.js
  src/extension-support/reporter-scope.js
Labels: pr - needs review

#992 Make "when clicked" blocks target dependent.
  src/blocks/scratch3_event.js
  src/engine/blocks.js
  src/io/mouse.js
  src/serialization/sb2.js
  src/virtual-machine.js
  test/fixtures/when-clicked.sb2
  test/unit/engine_blocks.js
  test/unit/serialization_sb2.js
Labels: pr - needs review

#979 SB3 Serialization & Load Project
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/serialization/serialize-assets.js
  src/virtual-machine.js
  test/unit/serialization_sb3.js
Labels: pr - needs work

#996 Position the speech bubble more tightly.
  src/blocks/scratch3_looks.js
  src/sprites/rendered-target.js
Labels: pr - needs review

#963 Implement for-each block
  src/blocks/scratch3_control.js
  src/serialization/sb2_specmap.js
  test/unit/blocks_control.js
Labels: pr - good to merge
