Repository scratchfoundation/scratch-vm, pull requests merged in 2018-12, with the labels that each got.

#1795 Serialize variable isCloud flag to xml.
  src/engine/variable.js
Labels: pr - good to merge

#1799 Add scratch-l10n dependency
  .travis.yml
  package-lock.json
  package.json
Labels: pr - good to merge

#1793 Remove vestigial device manager
  src/engine/runtime.js
  src/io/deviceManager.js
  test/unit/io_deviceManager.js
Labels: pr - good to merge

#1759 Make the wait block's logic and behavior more consistent with Scratch 2
  src/blocks/scratch3_control.js
  src/engine/block-utility.js
  src/engine/runtime.js
  src/engine/sequencer.js
  src/util/timer.js
  test/unit/blocks_control.js
Labels: compatibility, pr - good to merge

#1740 Fix flacky test: order-changes-backwards-2-broadcast-and-wait.sb2
  test/fixtures/execute/order-changes-backwards-2-broadcast-and-wait.sb2
Labels: pr - good to merge

#1803 Remove promise finally because we are having trouble with polyfills
  src/import/load-costume.js
Labels: pr - good to merge

#1804 Task Queue unit test stubbed timer
  test/unit/util_task-queue.js
Labels: pr - needs review

#1815 Clear the pen layer when runtime dispose happens.
  src/engine/runtime.js
  src/extensions/scratch3_pen/index.js
  test/unit/engine_runtime.js
Labels: pr - good to merge

#1819 Text to Speech use encodeURIComponent
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1741 Set video state after project load
  src/extensions/scratch3_video_sensing/index.js
  src/io/video.js
  src/serialization/sb2.js
  test/fixtures/load-extensions/README.md
  test/fixtures/load-extensions/confirm-load/ev3-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/microbit-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/music-simple-project.sb2
  test/fixtures/load-extensions/confirm-load/music-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/pen-dolphin-3d.sb2
  test/fixtures/load-extensions/confirm-load/pen-dolphin-3d.sb3
  test/fixtures/load-extensions/confirm-load/pen-simple-project.sb2
  test/fixtures/load-extensions/confirm-load/pen-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/text2speech-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/videoSensing-simple-project.sb2
  test/fixtures/load-extensions/confirm-load/videoSensing-simple-project.sb3
  test/fixtures/load-extensions/confirm-load/wedo2-simple-project.sb2
  test/fixtures/load-extensions/confirm-load/wedo2-simple-project.sb3
  test/fixtures/load-extensions/video-state/videoState-off.sb2
  test/fixtures/load-extensions/video-state/videoState-on-transparency-0.sb2
  test/integration/load-extensions.js
Labels: bug, compatibility, pr - good to merge

#1821 Fix an issue where the targetId of a monitor could be reassigned
  src/engine/blocks.js
Labels: pr - good to merge

#1816 Add a test and fix for not serializing top-level variable reporters
  src/serialization/sb3.js
  test/fixtures/top-level-variable-reporter.sb2
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1822 Make duplicateVariable deep copy the array instead of keeping reference.
  src/engine/target.js
  test/unit/engine_target.js
Labels: pr - good to merge

#1823 Request cloud variable update in top level setVariableValue API
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1825 Emit PROJECT_START event publicly on green flag click.
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1808 Skip task queue tests
  test/unit/util_task-queue.js
Labels: pr - good to merge

#1818 Clear out the blocks in dispose. Fixes #1758 where old monitored vari…
  src/engine/runtime.js
  src/engine/target.js
  src/virtual-machine.js
  test/fixtures/monitored_variables.sb3
  test/fixtures/timer-monitor.sb3
  test/integration/monitor-threads-run-every-frame.js
  test/integration/variable_monitor_reset.js
Labels: pr - good to merge

#1832 Makey Makey extension fixes
  src/extensions/scratch3_makeymakey/index.js
Labels: pr - good to merge

#1830 Fix sprite upload from vector image uploading at the wrong size
  src/import/load-costume.js
Labels: pr - good to merge

#1842 Serialize x and y for topLevel blocks even if they are 0
  src/serialization/sb3.js
  test/fixtures/top-level-reporters.sb3
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1834 Fix issue where edge-activated hats only run on one sprite after duplicating the sprite
  src/engine/execute.js
  src/engine/runtime.js
  src/engine/target.js
  src/sprites/rendered-target.js
  test/fixtures/edge-triggered-hat.sb3
  test/integration/hat-threads-run-every-frame.js
Labels: pr - good to merge

#1790 Add support for scratch 1.x MIDI drum blocks
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#1841 Update the translate language versions
  package-lock.json
  package.json
Labels: pr - good to merge

#1833 Fix issue importing some sb2s that were originally sb1s, with baseLayerMd5 property formatted differently.
  src/serialization/sb2.js
  test/fixtures/sb2-from-sb1-missing-backdrop-image.sb2
  test/integration/load-sb2-originally-sb1-without-backdrop-image.js
Labels: pr - good to merge

#1850 enable loading draggability from .sb3 file
  src/serialization/sb3.js
  test/fixtures/draggable.sb3
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1854 Prevent text to speech kitten voice from speaking names of punctuation
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1857 For order of Makey Makey extension's key pressed menu
  src/extensions/scratch3_makeymakey/index.js
Labels: pr - good to merge

#1853 Always pop the stack when the promised value is from the last op
  src/engine/execute.js
Labels: pr - needs review

#1849 Add addCostumeFromLibrary
  src/virtual-machine.js
Labels: pr - good to merge

#1840 Use default builtin SVG asset when an SVG can't be loaded
  src/import/load-costume.js
Labels: compatibility, pr - good to merge

#1852 depend on scratch-sb1-converter and convert sb1 files to sb2
  package-lock.json
  package.json
  src/virtual-machine.js
Labels: compatibility, pr - good to merge

#1864 Fix issue with uploading default vector image
  src/import/load-costume.js
Labels: pr - good to merge

#1868 Fix issue where uploading an sb with jpg images wasn't saving and loading
  src/import/load-costume.js
Labels: pr - needs review

#1874 Reject errors from loadCostume instead of logging
  src/import/load-costume.js
Labels: pr - needs review
