Repository scratchfoundation/scratch-vm, pull requests merged in 2018-06, with the labels that each got.

#1184 Set/change sound effect and volume blocks yield until the next tick
  src/blocks/scratch3_sound.js
Labels: pr - good to merge

#1188 fix: resolve scratch-*/src/index.js for expose-loader
  webpack.config.js
Labels: bug, pr - needs review

#1198 Update microbit extension for latest firmware
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1199 Add some log info with more information about the speech match so we …
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1203 APIs for getting and setting variable values
  src/engine/target.js
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1191 Persist comment state.
  src/engine/blocks.js
  src/engine/target.js
Labels: pr - good to merge

#1210 Add initial working version of the Amazon Polly extension
  src/extension-support/extension-manager.js
  src/extensions/scratch3_speak/index.js
Labels: pr - needs review

#1208 Increase maximum pen size to 1200
  src/extensions/scratch3_pen/index.js
Labels: pr - good to merge

#1215 Add webkitAudioContext if AudioContext does not exist. This might fix…
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1204 Add methods for reordering costumes and sounds
  src/sprites/rendered-target.js
  src/virtual-machine.js
  test/unit/sprites_rendered-target.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1217 Comment state fixes
  src/engine/blocks.js
Labels: pr - good to merge

#1222 Speech extension icons
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1218 Fix importing hidden monitors from Scratch 2 projects
  src/engine/blocks.js
  src/engine/runtime.js
Labels: pr - good to merge

#1209 Check that bubble bounds do not extend past stage boundaries
  src/blocks/scratch3_looks.js
Labels: pr - needs review

#1226 Implement "costume name" block
  src/serialization/sb2.js
  src/serialization/sb2_specmap.js
  test/unit/blocks_looks.js
Labels: pr - good to merge

#1229 Update position for comments imported from 2.0 projects after auto-positioning.
  src/engine/blocks.js
  test/fixtures/events.json
  test/unit/engine_target.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1231 Add top-level `reorderTarget` API to VM
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - needs work

#1211 yield a tick if broadcastandwait is waiting on threads waiting for a future tick
  src/blocks/scratch3_event.js
  src/blocks/scratch3_looks.js
  src/blocks/scratch3_sound.js
  src/engine/block-utility.js
  src/engine/runtime.js
Labels: pr - good to merge

#1233 Add extension status button
  src/engine/runtime.js
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1235 XML escape comment text.
  src/engine/comment.js
Labels: pr - good to merge

#1236 Comment Save & Load
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  test/fixtures/comments.sb3
  test/integration/comments_sb3.js
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1241 Clean up comment serialization
  src/serialization/sb3.js
  test/fixtures/comments_no_duplicate_id_serialization.sb3
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1240 Add comment id to block when converting from XML to vm representation.
  src/engine/adapter.js
  test/fixtures/events.json
  test/unit/engine_adapter.js
Labels: pr - good to merge

#1230 MicroBit extension, Scratch Link first draft.
  package.json
  src/extensions/scratch3_microbit/index.js
  src/io/peripheralChooser.js
  src/io/scratchBLE.js
  src/io/scratchBT.js
  src/util/base64-util.js
  src/util/jsonrpc-web-socket.js
  src/util/jsonrpc.js
  test/unit/extension_microbit.js
  test/unit/io_scratchBLE.js
  test/unit/io_scratchBT.js
  test/unit/util_base64.js
  test/unit/util_jsonrpc-web-socket.js
  test/unit/util_jsonrpc.js
Labels: pr - needs review

#1244 Add shareSound and shareCostume APIs with unit tests to the VM
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1246 Localize category labels
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_pen/index.js
  src/extensions/scratch3_translate/index.js
  src/extensions/scratch3_video_sensing/index.js
Labels: localization, pr - good to merge

#1248 Fix new sprites only showing up in the top-right quadrant
  src/sprites/rendered-target.js
Labels: pr - needs review

#1258 Use new scratch-audio APIs in music extension
  src/extensions/scratch3_music/index.js
Labels: pr - needs work

#1239 Use new scratch-audio SoundBank in vm / sounds
  src/blocks/scratch3_sound.js
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  test/unit/blocks_sounds.js
Labels: pr - good to merge

#1260 add decoded SoundPlayer's to a Sprite's SoundBank
  src/import/load-sound.js
  src/serialization/sb3.js
  src/virtual-machine.js
Labels: pr - good to merge

#1262 Revert #1260, #1258, #1239
  src/blocks/scratch3_sound.js
  src/extensions/scratch3_music/index.js
  src/import/load-sound.js
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/unit/blocks_sounds.js
Labels: pr - good to merge

#1263 Fix sound issue
  src/serialization/sb2.js
  src/sprites/sprite.js
  src/virtual-machine.js
Labels: pr - good to merge

#1264 Re-apply audio engine updates
  src/blocks/scratch3_sound.js
  src/extensions/scratch3_music/index.js
  src/import/load-sound.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/unit/blocks_sounds.js
Labels: pr - good to merge

#1256 Sprite save load
  src/engine/blocks.js
  src/engine/target.js
  src/serialization/sb3.js
  src/serialization/serialize-assets.js
  src/virtual-machine.js
  test/fixtures/events.json
  test/unit/engine_blocks.js
  test/unit/engine_target.js
Labels: pr - good to merge

#1266 stop drum immediately if it is still starting
  src/extensions/scratch3_music/index.js
Labels: pr - needs review

#1255 Serialize extensions used in a project
  src/serialization/sb3.js
Labels: pr - good to merge

#1270 Enable extension status button via XML attribute
  src/engine/runtime.js
Labels: pr - good to merge

#1254 Skip unknown opcode blocks while parsing
  src/serialization/sb2.js
  test/fixtures/unknown-opcode.sb2
  test/integration/unknown-opcode.js
Labels: pr - good to merge

#1277 Remove cache from Travis, begin using npm ci
  .gitignore
  .travis.yml
  package-lock.json
Labels: ci, pr - good to merge

#1282 chore(package): update eslint to version 5.0.1
  package.json
Labels: pr - good to merge
