Repository scratchfoundation/scratch-vm, pull requests merged in 2018-08, with the labels that each got.

#1413 Add turbo mode events
  src/engine/runtime.js
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1415 Import current block menu as field not input
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1397 Fix benchmark suite
  package.json
  src/playground/benchmark.js
  src/playground/index.html
  src/playground/suite.js
  webpack.config.js
Labels: pr - good to merge

#1434 Fix variable xml
  src/engine/target.js
  src/sprites/rendered-target.js
  test/unit/engine_target.js
Labels: pr - good to merge

#1398 Publish jsdoc to gh-pages
  .jsdoc.json
  package-lock.json
  package.json
  src/dispatch/shared-dispatch.js
  src/engine/runtime.js
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_video_sensing/index.js
  src/extensions/scratch3_wedo2/index.js
  src/serialization/sb2.js
  src/util/string-util.js
  src/virtual-machine.js
Labels: pr - good to merge

#1419 Use proposed drawableTouching interface from render
  src/sprites/rendered-target.js
  test/fixtures/fake-renderer.js
Labels: pr - good to merge

#1438 Export the sprite and return an add function when deleting the sprite.
  src/virtual-machine.js
  test/integration/delete-and-restore-sprite.js
Labels: pr - good to merge

#1441 WeDo2 Extension: First Pass
  src/extensions/scratch3_wedo2/index.js
  src/io/bleSession.js
Labels: pr - good to merge

#1431 Allow localizing micro:bit blocks
  src/extensions/scratch3_microbit/index.js
Labels: pr - needs review

#1437 Allow localizing EV3 blocks
  src/extensions/scratch3_ev3/index.js
Labels: pr - good to merge

#1469 Add WeDo 2.0 block icon
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge

#1481 Various WeDo2 fixes and enhancements
  src/extensions/scratch3_wedo2/index.js
  src/io/bleSession.js
Labels: pr - good to merge

#1471 Regulate micro:bit send timing
  src/extensions/scratch3_microbit/index.js
  src/io/bleSession.js
Labels: pr - good to merge

#1486 Fix issue with deleting sprite with local variables
  src/virtual-machine.js
Labels: pr - good to merge

#1453 round x and y like Scratch 2 does
  src/sprites/rendered-target.js
Labels: pr - good to merge

#1493 WeDo2 changes for upcoming smoke test
  src/extensions/scratch3_wedo2/index.js
  src/io/bleSession.js
Labels: pr - needs review

#1497 Revert "round x and y like Scratch 2 does"
  src/sprites/rendered-target.js
Labels: critical, pr - good to merge

#1494 Some small EV3 fixes
  src/extensions/scratch3_ev3/index.js
Labels: pr - good to merge

#1468 export deserializeBlocks method
  src/serialization/sb3.js
  test/unit/serialization_sb3.js
Labels: pr - good to merge

#1475 Use round() instead of floor() in repeat
  src/blocks/scratch3_control.js
  test/unit/blocks_control.js
Labels: pr - good to merge

#1503 Restore sound
  src/sprites/rendered-target.js
  src/virtual-machine.js
  test/unit/sprites_rendered-target.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1511 Restore costume
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/unit/sprites_rendered-target.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1427 Remove heuristic for bubble positioning that was not accurate.
  src/blocks/scratch3_looks.js
Labels: pr - good to merge

#1509 WeDo2 rate limiting
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge

#1512 WeDo2 Fixes
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge

#1515 Fix stack glow
  src/engine/blocks.js
  src/engine/execute.js
  src/engine/runtime.js
Labels: needs-qa, pr - good to merge

#1518 WeDo2 backwards compatibility update
  src/extensions/scratch3_wedo2/index.js
  src/io/bleSession.js
  src/io/btSession.js
Labels: pr - good to merge

#1522 Fix Comment Import
  src/serialization/sb2.js
  test/fixtures/block-to-workspace-comments.sb2
  test/integration/block_to_workspace_comment_import.js
Labels: pr - good to merge

#1467 Fix speech extension in Safari (#1202) by calling getUserMedia for ev…
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1476 Fix #1395 by resetting the utterance we check for in the edge trigger…
  src/extensions/scratch3_speech/index.js
Labels: pr - good to merge

#1524 Resolve project load error with undefined opcodes inside c/e blocks.
  src/serialization/sb2.js
  test/fixtures/unknown-opcode-in-c-block.sb2
  test/integration/unknown-opcode-in-c-block.js
Labels: needs-qa, pr - good to merge

#1528 Fix Comment import/save/load issue
  src/serialization/sb2.js
  test/fixtures/block-to-workspace-comments-without-scripts.sb2
  test/integration/block_to_workspace_comment_import_no_scripts.js
Labels: needs-qa, pr - good to merge

#1540 Rate-limiting with a token bucket for the WeDo extension
  src/extensions/scratch3_wedo2/index.js
  src/util/rateLimiter.js
  test/unit/util_rateLimiter.js
Labels: pr - good to merge

#1549 Update atob, format-message, adm-zip, docdash, format-message-cli, ta…
  package-lock.json
  package.json
Labels: greenkeeper
