Repository scratchfoundation/scratch-vm, pull requests merged in 2018-11, with the labels that each got.

#1711 Import cloud var info and enforce cloud var limit
  src/engine/runtime.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  test/fixtures/cloud_variables_exceeded_limit.sb2
  test/fixtures/cloud_variables_exceeded_limit.sb3
  test/fixtures/cloud_variables_limit.sb2
  test/fixtures/cloud_variables_limit.sb3
  test/fixtures/cloud_variables_local.sb2
  test/fixtures/cloud_variables_local.sb3
  test/fixtures/cloud_variables_simple.sb2
  test/fixtures/cloud_variables_simple.sb3
  test/integration/cloud_variables_sb2.js
  test/integration/cloud_variables_sb3.js
  test/unit/engine_runtime.js
Labels: pr - good to merge

#1718 Include the original blockId of the top block being dragged.
  src/engine/blocks.js
  src/engine/runtime.js
  src/virtual-machine.js
Labels: pr - good to merge

#1719 Handle images uploaded as sprites
  src/serialization/deserialize-assets.js
  src/serialization/sb3.js
Labels: pr - good to merge

#1709 Shortcut Cast.toNumber if given a number
  src/util/cast.js
Labels: performance, pr - good to merge

#1730 Make volume a sprite-specific monitor
  src/blocks/scratch3_sound.js
Labels: pr - good to merge

#1720 Use the new note picker field in music and EV3 extensions
  src/engine/runtime.js
  src/extension-support/argument-type.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#1683 Sequencer thread cleanup
  src/engine/runtime.js
  src/engine/sequencer.js
  test/fixtures/execute/event-broadcast-and-wait-can-continue-same-tick.sb2
  test/integration/hat-threads-run-every-frame.js
  test/integration/monitor-threads-run-every-frame.js
  test/integration/monitors.js
  test/unit/engine_sequencer.js
Labels: compatibility, pr - good to merge

#1649 Get attribute stage alt name
  src/serialization/sb2.js
  test/fixtures/execute/sensing-get-attribute-of-stage-alt-name.sb2
Labels: compatibility, pr - good to merge

#1727 Add unloaded extensions on block sharing
  src/serialization/sb3.js
  src/virtual-machine.js
  test/unit/serialization_sb3.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1742 Multi monitors
  package-lock.json
  src/blocks/scratch3_looks.js
  src/blocks/scratch3_sensing.js
  src/engine/blocks.js
  src/serialization/sb2.js
  src/util/get-monitor-id.js
  test/fixtures/monitors.sb2
  test/integration/monitors.js
Labels: pr - good to merge

#1696 Close Scratch Link web socket on every new peripheral scan attempt
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
Labels: pr - good to merge

#1697 Resolves #1687. Clear peripheral discover timeout when needed.
  src/io/ble.js
  src/io/bt.js
Labels: pr - good to merge

#1748 Implement "point towards random direction"
  src/blocks/scratch3_motion.js
Labels: compatibility, pr - good to merge

#1747 Always ignore video sensing monitor when importing from 2.0 and import visible extension monitors.
  src/serialization/sb2.js
  test/fixtures/invisible-tempo-monitor-no-other-music-blocks.sb2
  test/fixtures/load-extensions/music-visible-monitor-no-blocks.sb2
  test/fixtures/visible-tempo-monitor-no-other-music-blocks.sb2
  test/fixtures/visible-video-monitor-and-video-blocks.sb2
  test/fixtures/visible-video-monitor-no-other-video-blocks.sb2
  test/integration/sb2-import-extension-monitors.js
  test/unit/serialization_sb2.js
Labels: pr - good to merge

#1686 Monitor save & load
  src/engine/monitor-record.js
  src/engine/runtime.js
  src/serialization/sb3.js
  test/fixtures/monitors.sb3
  test/integration/monitors_sb2.js
  test/integration/monitors_sb3.js
Labels: pr - needs review

#1723 Cache the set of actively monitored blocks
  src/engine/blocks.js
Labels: performance, pr - good to merge

#1757 Use note picker in imported play note blocks
  src/serialization/sb2.js
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1755 Create cloud variables
  src/engine/blocks.js
  src/engine/runtime.js
  src/engine/target.js
  src/io/cloud.js
  test/unit/engine_target.js
  test/unit/io_cloud.js
Labels: pr - good to merge

#1750 Add method for collecting all targets' assets
  src/virtual-machine.js
  test/unit/vm_collectAssets.js
Labels: pr - good to merge

#1716 Handle unknown opcode in input
  src/serialization/sb2.js
  test/fixtures/unknown-opcode-as-reporter-block.sb2
  test/integration/unknown-opcode-as-reporter-block.js
Labels: pr - good to merge

#1722 Handle coordinate precision the same as Scratch 2
  src/blocks/scratch3_motion.js
  src/sprites/rendered-target.js
  test/unit/blocks_motion.js
Labels: compatibility, pr - good to merge

#1768 Fix unit tests on Travis CI
  .travis.yml
  test/unit/dispatch.js
Labels: pr - good to merge

#1770 Fix monitor tests to count only monitor threads
  test/integration/monitors_sb2.js
  test/integration/monitors_sb3.js
Labels: pr - good to merge

#1775 Cloud rename delete
  src/engine/target.js
  src/io/cloud.js
  test/unit/engine_target.js
  test/unit/io_cloud.js
Labels: pr - good to merge

#1737 Text layer
  src/import/load-costume.js
  src/serialization/deserialize-assets.js
  src/serialization/sb2.js
  src/serialization/sb3.js
Labels: pr - good to merge

#1735 Apply sprite's volume to music extension notes and drums
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#1779 Add "project changed" event
  src/engine/blocks.js
  src/engine/runtime.js
  src/virtual-machine.js
Labels: pr - good to merge

#1781 Adding check for open request before calling RPC reject/resolve.
  src/util/jsonrpc.js
Labels: pr - good to merge

#1783 Emit a RUNTIME_STARTED event to track if the vm has been started
  src/engine/runtime.js
  src/virtual-machine.js
  test/unit/engine_runtime.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1784 Make setLocale consistently refresh blocks
  src/virtual-machine.js
Labels: critical, pr - good to merge

#1785 Prevent the runtime from spawning new stepping intervals
  src/engine/runtime.js
  test/unit/engine_runtime.js
Labels: pr - good to merge

#1786 VM changes for the sensing_of block.
  src/blocks/scratch3_sensing.js
  src/engine/blocks.js
  src/engine/runtime.js
  src/virtual-machine.js
  test/unit/blocks_sensing.js
Labels: pr - good to merge

#1782 Makey Makey extension
  src/extension-support/extension-manager.js
  src/extensions/scratch3_makeymakey/index.js
Labels: pr - good to merge

#1754 Make Scratch 3 comparisons with +/-Infinity match Scratch 2
  src/engine/comment.js
  src/util/cast.js
  test/unit/blocks_data_infinity.js
  test/unit/blocks_operators.js
  test/unit/blocks_operators_infinity.js
Labels: pr - needs review
