Repository scratchfoundation/scratch-vm, pull requests merged in 2018-05, with the labels that each got.

#1086 Included a function to add sprite 3 to vm
  src/virtual-machine.js
Labels: pr - good to merge

#1093 Fix downloadProjectId method
  src/virtual-machine.js
Labels: pr - needs review

#1094 Add a project to benchmark sensing_touchingobject vs other sprites
  src/playground/suite.js
Labels: pr - needs review

#1102 "Implement" miscellaneous no-op obsolete blocks
  src/blocks/scratch3_looks.js
  src/blocks/scratch3_sensing.js
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1096 Implement "all at once" block
  src/blocks/scratch3_control.js
  src/serialization/sb2_specmap.js
  test/unit/blocks_control.js
Labels: pr - good to merge

#1099 "Implement" scroll blocks
  src/blocks/scratch3_motion.js
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1082 Add updateBitmap function. getCostume can now serve bitmaps as well as svgs
  package.json
  src/virtual-machine.js
Labels: pr - needs review

#1067 Boolean shadow regression test
  test/fixtures/execute/README.md
  test/fixtures/execute/control-if-false-then-else.sb2
  test/fixtures/execute/control-if-false-then.sb2
  test/fixtures/execute/control-if-true-then-else.sb2
  test/fixtures/execute/control-if-true-then.sb2
  test/fixtures/execute/event-when-green-flag.sb2
  test/fixtures/execute/operators-not-blank.sb2
  test/fixtures/execute/procedures-number-number-boolean.sb2
  test/integration/execute.js
Labels: pr - good to merge

#1085 Re-write keyboard IO for droppability support
  src/io/keyboard.js
  test/unit/io_keyboard.js
Labels: pr - good to merge

#1008 Implement "item # of (thing) in (list)" block
  src/blocks/scratch3_data.js
  test/unit/blocks_data.js
Labels: pr - good to merge

#1111 Use arraybuffer-loader in place of buffer-loader
  package.json
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_music/manifest.js
Labels: pr - good to merge

#1114 Fix broken rotation center on vector sprites
  src/virtual-machine.js
Labels: pr - needs review

#1110 Support for Sprite Upload
  package.json
  src/blocks/scratch3_sensing.js
  src/serialization/sb3.js
  src/virtual-machine.js
  test/fixtures/example_sprite.sprite2
  test/integration/addSprite.js
  test/integration/complex.js
  test/unit/spec.js
  test/unit/virtual-machine.js
Labels: pr - needs review

#1104 Update to webpack 4
  package.json
  webpack.config.js
Labels: pr - good to merge

#1105 Dynamically load music extension manifest
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#1118 Add Thread.StackFrame class
  src/engine/block-utility.js
  src/engine/execute.js
  src/engine/thread.js
Labels: pr - good to merge

#1119 Recycle block args
  src/engine/blocks.js
  src/engine/execute.js
Labels: pr - good to merge

#1129 Clean up Travis config
  .travis.yml
  package.json
Labels: pr - good to merge

#1130 Make Travis release stage conditional by branch
  .travis.yml
Labels: pr - good to merge

#1122 Handle random backdrop menu option
  src/blocks/scratch3_looks.js
Labels: pr - good to merge

#1127 Update scratch-parser.
  package.json
Labels: pr - needs review

#1128 Import monitors from sb2 files.
  src/blocks/scratch3_data.js
  src/blocks/scratch3_looks.js
  src/blocks/scratch3_motion.js
  src/blocks/scratch3_sensing.js
  src/blocks/scratch3_sound.js
  src/engine/blocks.js
  src/engine/execute.js
  src/engine/monitor-record.js
  src/engine/runtime.js
  src/serialization/sb2.js
  src/serialization/sb2_specmap.js
  src/virtual-machine.js
  test/fixtures/hat-execution-order.sb2
  test/fixtures/looks.sb2
  test/fixtures/monitors.sb2
  test/integration/monitors.js
Labels: pr - good to merge

#1134 Actually do the deploy
  .travis.yml
Labels: pr - good to merge

#1126 Run quirks mode fixes on costumes loaded from sb2s
  src/engine/runtime.js
  src/import/load-costume.js
  src/serialization/sb2.js
  src/virtual-machine.js
Labels: pr - needs review

#1136 Add localization support to music and video sensing extensions
  package.json
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_video_sensing/index.js
Labels: pr - needs review

#1133 Add implementations for hiding and showing variables and lists.
  src/blocks/scratch3_data.js
Labels: pr - needs review

#1141 Add extension id to toolbox category XML
  src/engine/runtime.js
Labels: pr - good to merge

#1142 Update tx/config for Scratch 3.0
  .tx/config
Labels: pr - good to merge

#1143 Revert "Dynamically load music extension manifest"
  src/extensions/scratch3_music/index.js
Labels: pr - good to merge

#1140 Add translate extension to the extension manager.
  src/extension-support/extension-manager.js
Labels: pr - needs review

#1138 Update the format of the language menu to match the changes made to d…
  src/extensions/scratch3_translate/index.js
Labels: pr - needs review

#1113 Add micro:bit Scratch 3.0 extension
  src/extension-support/extension-manager.js
  src/extensions/scratch3_microbit/index.js
Labels: pr - needs review

#1149 Pass in argument to indicate compat mode
  src/import/load-costume.js
Labels: pr - good to merge

#1147 Fix say bug with show/hide
  src/blocks/scratch3_looks.js
Labels: needs-discussion, pr - needs review

#1159 Translation extension imports translated language names
  package.json
  src/extensions/scratch3_translate/index.js
Labels: pr - good to merge

#1162 Runtime emits key pressed event
  src/blocks/scratch3_event.js
  src/io/keyboard.js
Labels: pr - good to merge

#1156 Publish specific files and folders to NPM
  .npmignore
Labels: ergonomics, pr - good to merge

#1163 Add logged out version of username block
  src/blocks/scratch3_sensing.js
  test/unit/blocks_sensing.js
Labels: pr - good to merge

#1160 Round (x position) and (y position) to 8 places
  src/sprites/rendered-target.js
Labels: pr - good to merge

#1132 Only run before_deploy once during deployment
  .travis.yml
Labels: pr - good to merge

#1164 Always give backdrops a certain rotation center
  src/serialization/sb2.js
Labels: pr - good to merge

#1167 Fix syntax error
  .travis.yml
Labels: pr - good to merge

#1153 Add option for Extensions to have different colour
  .gitignore
  src/engine/runtime.js
Labels: pr - good to merge

#1148 Layer group ordering.
  src/blocks/scratch3_looks.js
  src/engine/runtime.js
  src/engine/stage-layering.js
  src/extensions/scratch3_pen/index.js
  src/io/video.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  src/sprites/sprite.js
  test/fixtures/fake-renderer.js
  test/unit/sprites_rendered-target.js
Labels: pr - good to merge

#1171 Allow rotation centers with zeros
  src/import/load-costume.js
Labels: pr - good to merge

#1181 Translate block defaults to a random language
  src/extensions/scratch3_translate/index.js
Labels: pr - good to merge

#1121 Initial version of the speech extension. There is certainly still so…
  package.json
  src/extension-support/extension-manager.js
  src/extensions/scratch3_speech/assets/speech-rec-end.mp3
  src/extensions/scratch3_speech/assets/speech-rec-start.mp3
  src/extensions/scratch3_speech/index.js
  src/extensions/scratch3_speech/manifest.js
Labels: pr - needs review

#1106 Use src/index as browser entry point
  package.json
  src/playground/index.html
  webpack.config.js
Labels: pr - good to merge

#1180 Import Comments from 2.0 Projects
  src/engine/blocks.js
  src/engine/comment.js
  src/engine/target.js
  src/serialization/sb2.js
  src/sprites/rendered-target.js
  src/virtual-machine.js
  test/fixtures/comments.sb2
  test/integration/comments.js
  test/integration/import_sb2.js
  test/unit/engine_target.js
  test/unit/serialization_sb2.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1185 Make canvas-toBlob a dependency
  package.json
Labels: pr - good to merge

#1186 Clean up the rest of the dependencies
  package.json
Labels: pr - good to merge
