Repository scratchfoundation/scratch-vm, pull requests merged in 2018-10, with the labels that each got.

#1586 conflict workaround for variables and lists of the same name
  src/serialization/sb2.js
  test/fixtures/execute/data-operators-global.sb2
  test/fixtures/execute/data-operators-local.sb2
  test/fixtures/execute/data-reporter-contents-global.sb2
  test/fixtures/execute/data-reporter-contents-local.sb2
Labels: pr - good to merge

#1585 Bubble string length limit
  src/blocks/scratch3_looks.js
Labels: pr - needs review

#1593 Fix locale-dependant string comparison operators to match 2.0
  src/util/cast.js
  test/unit/blocks_operators.js
Labels: pr - needs review

#1619 Execution order 2
  src/blocks/scratch3_event.js
  src/blocks/scratch3_looks.js
  src/sprites/rendered-target.js
  test/fixtures/execute/events-broadcast-and-wait-yields-a-tick.sb2
  test/fixtures/execute/order-changes-back-2-broadcast-wait.sb2
  test/fixtures/execute/order-changes-backwards-2-broadcast-and-wait-repeat-message.sb2
  test/fixtures/execute/order-changes-backwards-2-broadcast-and-wait.sb2
  test/fixtures/execute/order-changes-backwards-2-broadcast-no-wait.sb2
  test/fixtures/execute/order-changes-backwards-2-broadcast-wait.sb2
  test/fixtures/execute/order-changes-backwards-2-continuous.sb2
  test/fixtures/execute/order-changes-backwards-2-threads-broadcast-wait.sb2
  test/fixtures/execute/order-changes-forewards-2-broadcast-wait.sb2
  test/fixtures/execute/order-changes-front-2-broadcast-wait.sb2
  test/fixtures/execute/order-clones-backwards-2-broadcast-wait.sb2
  test/fixtures/execute/order-clones-backwards-broadcast-wait.sb2
  test/fixtures/execute/order-clones-static-2.sb2
  test/fixtures/execute/order-immobile-stage.sb2
  test/unit/blocks_event.js
Labels: compatibility, pr - good to merge

#1630 Hardware extensions: fixes and menu localization
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
Labels: pr - good to merge

#1652 Add icons for Video Sensing, Translate and Text to Speech extensions
  src/extensions/scratch3_text2speech/index.js
  src/extensions/scratch3_translate/index.js
  src/extensions/scratch3_video_sensing/index.js
Labels: pr - good to merge

#1636 Consistently return promises from functions that say they return promises
  src/import/load-costume.js
Labels: pr - good to merge

#1655 Text to Speech voices update
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1657 Remove "Don't translate Google"
  src/extensions/scratch3_speech2text/index.js
Labels: pr - needs review

#1631 Stop other asks
  src/blocks/scratch3_sensing.js
  src/engine/runtime.js
  test/unit/blocks_sensing.js
Labels: compatibility, pr - good to merge

#1667 Update babel-eslint to version 10.0.1
  package-lock.json
  package.json
Labels: pr - good to merge

#1668 Update babel-loader to version 8.0.4
  package-lock.json
  package.json
  webpack.config.js
Labels: pr - good to merge

#1643 Confirm extension in use in sb2 serialization
  src/engine/runtime.js
  src/extensions/scratch3_video_sensing/index.js
  src/serialization/sb2.js
  test/fixtures/extensions-in-blocks.sb2
  test/fixtures/extensions-in-monitors.sb2
  test/fixtures/extensions-not-serialized.sb2
  test/unit/serialization_sb2.js
Labels: pr - needs review

#1654 Differentiate peripheral errors: request vs. disconnect
  src/engine/runtime.js
  src/io/ble.js
  src/io/bt.js
  src/virtual-machine.js
Labels: pr - good to merge

#1670 Save and load the language setting for Text to Speech
  src/extensions/scratch3_text2speech/index.js
  src/serialization/sb3.js
  src/sprites/rendered-target.js
Labels: pr - good to merge

#1675 Revert "Confirm extension in use in sb2 serialization"
  src/engine/runtime.js
  src/extensions/scratch3_video_sensing/index.js
  src/serialization/sb2.js
  test/fixtures/extensions-in-blocks.sb2
  test/fixtures/extensions-in-monitors.sb2
  test/fixtures/extensions-not-serialized.sb2
  test/unit/serialization_sb2.js
Labels: critical, pr - needs review

#1680 Update copy-webpack-plugin to version 4.5.4
  package-lock.json
  package.json
Labels: pr - good to merge

#1642 Set procedure param defaults
  src/blocks/scratch3_procedures.js
  src/engine/block-utility.js
  src/engine/blocks.js
  test/fixtures/execute/procedures-recursive-default-boolean.sb2
  test/fixtures/execute/procedures-recursive-default-number.sb2
  test/fixtures/execute/procedures-recursive-default-string.sb2
  test/unit/blocks_procedures.js
Labels: compatibility, pr - good to merge

#1688 Prevent invisible monitors from loading extensions
  src/serialization/sb2.js
  test/fixtures/invisible-video-monitor.sb2
  test/unit/serialization_sb2.js
Labels: extensions, pr - good to merge

#1640 Set procedure param missing
  src/blocks/scratch3_procedures.js
  src/engine/thread.js
  test/fixtures/execute/procedures-nested-missing-boolean-param.sb2
  test/fixtures/execute/procedures-nested-missing-number-param.sb2
  test/fixtures/execute/procedures-nested-missing-string-param.sb2
  test/fixtures/execute/procedures-param-outside-boolean.sb2
  test/fixtures/execute/procedures-param-outside-number.sb2
  test/fixtures/execute/procedures-param-outside-string.sb2
Labels: compatibility, pr - good to merge

#1691 Store asset objects on costumes and sounds
  package-lock.json
  package.json
  src/import/load-costume.js
  src/import/load-sound.js
  src/serialization/deserialize-assets.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/serialization/serialize-assets.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/integration/offline-custom-assets.js
Labels: pr - good to merge

#1517 Make "switch costume" and "switch backdrop" blocks compatible with 2.0
  src/blocks/scratch3_looks.js
  src/sprites/rendered-target.js
  test/unit/blocks_looks.js
Labels: pr - good to merge

#1416 Make click hats trigger on mouse down instead of up
  src/io/mouse.js
  test/unit/io_mouse.js
Labels: pr - good to merge

#1703 Cloud IO
  package-lock.json
  src/blocks/scratch3_data.js
  src/engine/runtime.js
  src/io/cloud.js
  src/virtual-machine.js
  test/unit/io_cloud.js
Labels: pr - good to merge

#1700 Tests to check whether extensions load
  test/fixtures/load-extensions/README.md
  test/fixtures/load-extensions/ev3-simple-project.sb3
  test/fixtures/load-extensions/microbit-simple-project.sb3
  test/fixtures/load-extensions/music-simple-project.sb2
  test/fixtures/load-extensions/music-simple-project.sb3
  test/fixtures/load-extensions/pen-dolphin-3d.sb2
  test/fixtures/load-extensions/pen-dolphin-3d.sb3
  test/fixtures/load-extensions/pen-simple-project.sb2
  test/fixtures/load-extensions/pen-simple-project.sb3
  test/fixtures/load-extensions/text2speech-simple-project.sb3
  test/fixtures/load-extensions/wedo2-simple-project.sb2
  test/fixtures/load-extensions/wedo2-simple-project.sb3
  test/integration/load-extensions.js
Labels: compatibility, extensions, pr - good to merge
