Repository scratchfoundation/scratch-vm, pull requests merged in 2018-09, with the labels that each got.

#1555 Refactor for hardware extensions
  src/engine/runtime.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
  src/virtual-machine.js
  test/unit/io_scratchBLE.js
  test/unit/io_scratchBT.js
Labels: pr - good to merge

#1569 Remove branding from translate extension
  src/extensions/scratch3_translate/index.js
Labels: pr - good to merge

#1564 Rename Stage object and Stage monitors together
  src/playground/suite.js
  src/serialization/sb2.js
  test/fixtures/execute/monitors-stage-name.sb2
  test/integration/execute.js
Labels: pr - good to merge

#1574 Trim text2speech string to 128 chars
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1573 Bark bark woof ruff bark. Bark bark bark! (remove puppy voice)
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1565 Extension monitors
  src/engine/runtime.js
  src/extension-support/extension-metadata.js
  test/unit/engine_runtime.js
Labels: pr - needs review

#1575 Remove sound indicators at the start/end of listen block. Visual rep…
  src/extensions/scratch3_speech/assets/speech-rec-end.mp3
  src/extensions/scratch3_speech/assets/speech-rec-start.mp3
  src/extensions/scratch3_speech/index.js
  src/extensions/scratch3_speech/manifest.js
Labels: pr - good to merge

#1583 Fx ids and names for text2speech and speech2text extensions
  src/extension-support/extension-manager.js
  src/extensions/scratch3_speech2text/index.js
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1563 Get param condition input
  src/serialization/sb2.js
  src/serialization/sb2_specmap.js
  test/fixtures/execute/procedures-boolean-reporter-bug.sb2
Labels: pr - good to merge

#1594 Add API for the attached renderer
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#1597 Rename block "display [Hello!]" to "display text [Hello!]"
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1587 Add a rate-limited task queue utility
  src/util/task-queue.js
  test/fixtures/test-compare.js
  test/unit/util_task-queue.js
Labels: pr - needs review

#1602 Bump `request` version in package-lock.json
  package-lock.json
Labels: pr - good to merge

#1610 Add “set language” block for the Text to Speech extension
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1598 Trim whitespace in "display [♡]" input field
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1600 Remove the word "test" from 'when pin connected' block
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1606 Change “monster” to “giant” and raise pitch
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1607 Show customized alerts on hardware extension peripheral errors.
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
  src/virtual-machine.js
Labels: pr - good to merge

#1599 Make "display [Hello!] block yield until printing is done
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1329 Add support for "midiInstrument:" block
  src/extensions/scratch3_music/index.js
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1611 Hardware extensions bug fixes
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge

#1618 Fix midi instruments doc
  src/extensions/scratch3_music/index.js
Labels: ci, pr - good to merge
