Repository scratchfoundation/scratch-vm, pull requests merged in 2019-06, with the labels that each got.

#2182 Initial prototype of configurable scratch link socket
  src/engine/runtime.js
  src/io/ble.js
  src/io/bt.js
  src/util/jsonrpc-web-socket.js
  src/util/scratch-link-websocket.js
  src/virtual-machine.js
Labels: pr - needs review

#2191 Add optional 'pin' parameter to BT connections
  src/extensions/scratch3_ev3/index.js
  src/io/bt.js
Labels: pr - good to merge

#2070 Add RateLimiter to EV3
  src/extensions/scratch3_ev3/index.js
Labels: pr - good to merge

#2197 Update sound duration
  src/virtual-machine.js
Labels: pr - needs review

#2084 Fixing some translate language menu bugs.
  package-lock.json
  package.json
  src/extensions/scratch3_translate/index.js
Labels: pr - good to merge

#2194 GDXFOR: Rename scratchLinkSocket variables to 'socket' and 'ble'
  src/extensions/scratch3_gdx_for/index.js
  src/extensions/scratch3_gdx_for/scratch-link-device-adapter.js
Labels: pr - good to merge

#2207 Removing comment in WeDo2 extension
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge

#2161 Supporting VM changes for extensionification
  docs/extensions.md
  src/engine/blocks.js
  src/engine/mutation-adapter.js
  src/engine/runtime.js
  src/extension-support/extension-manager.js
  src/virtual-machine.js
  test/integration/internal-extension.js
  test/unit/engine_blocks.js
  test/unit/engine_mutation-adapter.js
  test/unit/extension_conversion.js
Labels: pr - good to merge

#2143 support non-droppable menus in extensions
  docs/extensions.md
  src/engine/runtime.js
  src/extension-support/extension-manager.js
  src/extensions/scratch3_boost/index.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_gdx_for/index.js
  src/extensions/scratch3_makeymakey/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_music/index.js
  src/extensions/scratch3_pen/index.js
  src/extensions/scratch3_text2speech/index.js
  src/extensions/scratch3_translate/index.js
  src/extensions/scratch3_video_sensing/index.js
  src/extensions/scratch3_wedo2/index.js
Labels: extensions, pr - needs review

#2163 Add support for custom context menu items to the extension spec.
  docs/extensions.md
  src/blocks/scratch3_core_example.js
  src/extension-support/context-menu-context.js
  src/extension-support/extension-manager.js
  test/integration/internal-extension.js
Labels: pr - good to merge

#2201 Clean up hardware disconnect behavior
  src/extensions/scratch3_boost/index.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_gdx_for/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
Labels: pr - good to merge

#2211 EV3 documentation and small refactors
  src/extensions/scratch3_ev3/index.js
Labels: pr - good to merge
