Repository scratchfoundation/scratch-vm, pull requests merged in 2019-05, with the labels that each got.

#2164 Do not localize BOOST motor IDs
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2126 Runtime script cache fix
  src/engine/blocks-runtime-cache.js
  src/engine/blocks.js
  src/engine/runtime.js
  src/engine/sequencer.js
  test/integration/hat-threads-run-every-frame.js
Labels: performance, pr - good to merge

#1648 Stop all next tick
  src/engine/runtime.js
  src/engine/sequencer.js
  test/fixtures/execute/control-stop-all-leaks.sb2
Labels: compatibility, pr - good to merge

#2175 Do not load speech2text extension
  src/extension-support/extension-manager.js
Labels: pr - needs review

#2168 Change BOOST variable names regarding duration and rotation blocks
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2181 Revert unwanted changes
  src/extension-support/extension-manager-old.js
  src/extension-support/extension-manager.js
  src/extensions/scratch3_lightplay/index.js
  src/extensions/scratch3_synth/index.js
  src/extensions/scratch3_synth/tone.js
Labels: pr - good to merge
