Repository scratchfoundation/scratch-vm, pull requests merged in 2019-02, with the labels that each got.

#1945 Escape variable name in XML
  src/engine/variable.js
  test/unit/engine_variable.js
Labels: pr - good to merge

#1967 GDXFOR sensor array refactor
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1962 Project dirty state fixes
  src/engine/blocks.js
  src/engine/runtime.js
  src/virtual-machine.js
  test/fixtures/cat.sprite2
  test/fixtures/cat.sprite3
  test/integration/running_project_changed_state.js
  test/unit/project_changed_state.js
  test/unit/project_changed_state_blocks.js
  test/unit/project_load_changed_state.js
Labels: QA-OK, pr - good to merge

#1973 Fix variable characters
  src/engine/target.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/util/string-util.js
  src/util/variable-util.js
  test/fixtures/variable_characters.sb2
  test/fixtures/variable_characters.sb3
  test/integration/variable_special_chars_sb2.js
  test/integration/variable_special_chars_sb3.js
  test/unit/util_string.js
  test/unit/util_variable.js
Labels: pr - good to merge

#1978 Vernier gdxfor extension: add spacers and rename "spin"
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1979 Add a utility for giving blocks new IDs, use it for sharing blocks.
  src/util/new-block-ids.js
  src/virtual-machine.js
  test/fixtures/simple-stack.js
  test/unit/util_new-block-ids.js
  test/unit/virtual-machine.js
Labels: pr - needs review

#1983 Broadcast msg chars
  src/engine/blocks.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/util/variable-util.js
  test/fixtures/broadcast_special_chars.sb2
  test/fixtures/broadcast_special_chars.sb3
  test/fixtures/events.json
  test/integration/broadcast_special_chars_sb2.js
  test/integration/broadcast_special_chars_sb3.js
  test/integration/variable_special_chars_sb3.js
  test/unit/engine_blocks.js
Labels: pr - needs review

#1982 GDX-FOR better freefall algorithm and different tilt options
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1985 Fix issue where non-strings were getting passed in to escape functions
  src/util/string-util.js
  src/util/xml-escape.js
  test/unit/util_string.js
  test/unit/util_xml.js
Labels: pr - needs review

#1984 Vernier gdxfor input rate change
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1986 Vernier gdxfor "falling?" report false when not connected
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1933 Feature/field type support
  src/engine/runtime.js
  src/virtual-machine.js
Labels: pr - good to merge

#1993 handle sb2 files zipped in a folder
  package-lock.json
  package.json
  src/serialization/deserialize-assets.js
  test/fixtures/default_nested.sb2
  test/fixtures/readProjectFile.js
  test/integration/import_nested_sb2.js
Labels: compatibility, pr - good to merge

#1995 Support isDiscrete flag on monitors
  src/engine/monitor-record.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  test/fixtures/monitors.sb2
  test/integration/monitors_sb2.js
  test/integration/monitors_sb2_to_sb3.js
  test/integration/monitors_sb3.js
Labels: pr - needs review

#1871 Fix dynamic menus for string arrays
  src/extension-support/extension-manager.js
Labels: pr - good to merge

#1881 Change legacy pen color block's behavior
  src/extensions/scratch3_pen/index.js
Labels: critical, pr - good to merge

#1990 Vernier gdxfor tilt values 0 when disconnected
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1944 Benchmark load time
  src/playground/benchmark.js
  src/playground/index.html
  webpack.config.js
Labels: performance, pr - good to merge

#2008 Vernier Force & Accel extension updates
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1969 Benchmark more data
  src/playground/benchmark.js
  src/playground/index.html
Labels: performance, pr - good to merge

#1959 Declare const once to be reused in for loop
  src/engine/runtime.js
Labels: performance, pr - good to merge

#2003 Depend on uglifyjs-webpack-plugin
  package.json
Labels: ergonomics, pr - good to merge

#1998 Task queue enhancements
  src/util/task-queue.js
  src/util/timer.js
  test/fixtures/mock-timer.js
  test/unit/mock-timer.js
  test/unit/util_task-queue.js
  test/unit/util_timer.js
Labels: pr - good to merge
