Repository scratchfoundation/scratch-vm, pull requests merged in 2019-03, with the labels that each got.

#1947 Deserialize sb2 assets before other sprite data and blocks
  src/serialization/sb2.js
Labels: QA-OK, performance, pr - good to merge

#1972 Sound bank over sprite
  src/import/load-sound.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/sprites/sprite.js
  src/virtual-machine.js
Labels: QA-OK, performance, pr - good to merge

#2014 Fix micro:bit auto-disconnect from setInterval to setTimeout
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#1981 update text-encoding to latest version
  package-lock.json
  package.json
Labels: performance, pr - good to merge

#1970 Use Promise.all, createImageBitmap, and one canvas in `load-costume.js`
  src/import/load-costume.js
Labels: performance, pr - good to merge

#2038 Cast sprite name to string before getSpriteTargetByName
  src/blocks/scratch3_motion.js
  src/blocks/scratch3_sensing.js
  src/sprites/rendered-target.js
  test/fixtures/execute/sprite-number-name.sb2
Labels: compatibility, pr - good to merge

#1956 Lazy eval big dependencies
  src/extension-support/extension-manager.js
  src/virtual-machine.js
Labels: performance, pr - good to merge

#2042 add clampEffect for limiting range of brightness and ghost effects
  src/blocks/scratch3_looks.js
  test/unit/blocks_looks.js
Labels: compatibility, pr - good to merge

#2045 Allow for situation where we get a move event to attach a shadow.
  src/engine/blocks.js
  test/unit/engine_blocks.js
Labels: pr - good to merge

#2043 Device scan discovery fix
  src/io/ble.js
  src/io/bt.js
Labels: pr - good to merge

#2024 Rate limiting for micro:bit using TaskQueue
  src/extensions/scratch3_microbit/index.js
Labels: pr - good to merge

#2046 Add eight new languages to Text to Speech extension
  src/extensions/scratch3_text2speech/index.js
  test/unit/extension_text_to_speech.js
Labels: pr - good to merge

#2009 Deserialize sb3 assets before loading data
  src/serialization/sb3.js
Labels: performance, pr - good to merge

#2055 Fix hardware extension disconnect behavior
  src/io/ble.js
  src/io/bt.js
Labels: critical, pr - good to merge

#2058 Remove Hindi from text2speech extension
  src/extensions/scratch3_text2speech/index.js
Labels: pr - needs review

#2059 Add Hindi language to Text to Speech
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#2063 Move facing options into gesture menu
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#2068 Stabilize Vernier "turned faced up/down" hat events
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#2069 Load Vernier extension code
  src/extension-support/extension-manager.js
Labels: pr - good to merge

#2060 Load core extensions synchronously
  src/blocks/scratch3_core_example.js
  src/dispatch/central-dispatch.js
  src/extension-support/extension-manager.js
  src/virtual-machine.js
  test/integration/internal-extension.js
  test/unit/dispatch.js
Labels: pr - needs review
