Repository scratchfoundation/scratch-vm, pull requests merged in 2019-04, with the labels that each got.

#2083 Allow extensions to make buttons
  src/blocks/scratch3_core_example.js
  src/engine/runtime.js
  src/extension-support/block-type.js
  src/extension-support/extension-manager.js
  test/integration/internal-extension.js
  test/unit/extension_conversion.js
Labels: extensions, feature, pr - good to merge

#2061 Add LEGO BOOST Scratch 3.0 extension
  src/extension-support/extension-manager.js
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2099 Fix #2085 by handling discarded hub commands
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2100 Fix 2087, 2088, and 2089 by properly setting parameters in rotation-commands and not using command feedback when relying on scratch-vm for motor timing
  src/extensions/scratch3_boost/index.js
  src/util/math-util.js
Labels: pr - good to merge

#2101 Fix #2086 by resolving pending promise even when power set to 0%
  src/extensions/scratch3_boost/index.js
Labels: needs discussion, pr - needs work

#2106 Fix #2105 by correctly accessing motor position from BoostMotor-class
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2065 Fix #4573 by using an existing utitlity that re-ids blocks when we du…
  src/sprites/sprite.js
  test/unit/sprites_rendered-target.js
Labels: pr - good to merge

#2107 Fix BOOST whenColor hat
  src/extensions/scratch3_boost/index.js
Labels: pr - needs review

#2111 Fix #2103 and #2110 by clearly defining motor state and how it's modified
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2115 Fix #2108 by making setMotorPower() and setMotorDirection() yield for a tick
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2041 Set canvas and costume size to zero if bitmap is empty
  src/virtual-machine.js
Labels: compatibility, pr - needs review

#2119 BOOST color sensing fixes
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#1930 Cache hat block information for the runtime
  src/engine/blocks-runtime-cache.js
  src/engine/blocks.js
  src/engine/runtime.js
  test/integration/hat-threads-run-every-frame.js
Labels: performance, pr - good to merge

#2071 Stub timer to fix flaky test
  test/unit/util_timer.js
Labels: pr - good to merge

#2098 Extension docs
  docs/extensions.md
Labels: documentation, pr - needs review

#2123 use xmlEscape instead of escape-html for extensions
  package-lock.json
  package.json
  src/engine/runtime.js
  webpack.config.js
Labels: pr - good to merge

#2132 Make Boost set motor speed opcode yield for send interval duration
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2131 Add Arabic to Text to Speech extension
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#2139 Reverse the sign on Boost Motor A position reporter
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2141 Add a runtime event for requesting a toolbox update
  src/engine/runtime.js
  src/virtual-machine.js
Labels: pr - needs review

#2140 Change Boost motor turning behavior for '0 speed' case
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2133 Prevent Boost turnOnForDegrees jittering on power set
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2159 Make BOOST extension displayed name all-caps
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2160 BOOST extension: Always clear motor promises when setting state
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge
