Repository scratchfoundation/scratch-vm, pull requests merged in 2019-07, with the labels that each got.

#2225 Add docs and example for custom context menu callback with access to blockInfo.
  docs/extensions.md
  src/blocks/scratch3_core_example.js
Labels: pr - good to merge

#2227 Add API for attaching a block updater callback function to the VM
  src/engine/runtime.js
  src/virtual-machine.js
  test/unit/virtual-machine.js
Labels: pr - good to merge

#2145 Raise params to the next frame when pushing
  src/blocks/scratch3_procedures.js
  src/engine/block-utility.js
  src/engine/execute.js
  src/engine/runtime.js
  src/engine/sequencer.js
  src/engine/thread.js
  test/fixtures/execute/procedures-stop-this-script-ends.sb2
  test/unit/engine_sequencer.js
  test/unit/engine_thread.js
Labels: performance, pr - needs work

#2240 Revert "Raise params to the next frame when pushing"
  src/blocks/scratch3_procedures.js
  src/engine/block-utility.js
  src/engine/execute.js
  src/engine/runtime.js
  src/engine/sequencer.js
  src/engine/thread.js
  test/fixtures/execute/procedures-stop-this-script-ends.sb2
  test/unit/engine_sequencer.js
  test/unit/engine_thread.js
Labels: pr - good to merge

#2242 Variable Renaming Context Menu Item
  docs/extensions.md
  src/blocks/data.js
  src/blocks/scratch3_core_example.js
  src/engine/blocks.js
  src/engine/runtime.js
  src/engine/target.js
  src/extension-support/extension-manager.js
  src/virtual-machine.js
  test/integration/internal-extension.js
Labels: pr - needs review

#2235 Fix 2232 by using unregulated motor command to turn off motors
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge

#2229 Fix 2215 by properly remapping ports to fit new firmware changes
  src/extensions/scratch3_boost/index.js
Labels: pr - good to merge
