Repository scratchfoundation/scratch-vm, pull requests merged in 2019-01, with the labels that each got.

#1884 Generate md5s for uploaded assets
  src/serialization/deserialize-assets.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  test/integration/complex.js
  test/integration/import-sb2-from-object.js
  test/integration/import_sb2.js
  test/integration/load-sb2-originally-sb1-without-backdrop-image.js
  test/integration/sb3-roundtrip.js
Labels: critical, pr - needs review

#1878 Clamp ghost effect
  src/blocks/scratch3_looks.js
Labels: critical, pr - good to merge

#1869 Always use English for kitten
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1899 Do not deep clone before serializing.
  src/serialization/sb3.js
Labels: pr - good to merge

#1898 Re enable tests that were unavailable during maintenance
  test/integration/complex.js
  test/integration/import-sb2-from-object.js
  test/integration/import_sb2.js
  test/integration/load-sb2-originally-sb1-without-backdrop-image.js
  test/integration/sb3-roundtrip.js
Labels: pr - good to merge

#1900 Clamp the currentCostume number when loading a project
  src/serialization/sb2.js
  src/serialization/sb3.js
Labels: pr - needs work

#1903 Add legacy drum block to specmap
  src/serialization/sb2_specmap.js
Labels: pr - good to merge

#1902 Allow projects with unknown monitors to load.
  src/serialization/sb2.js
Labels: pr - needs review

#1905 Add Vernier's GDX-FOR extension
  package-lock.json
  package.json
  src/extension-support/extension-manager.js
  src/extensions/scratch3_gdx_for/index.js
  src/extensions/scratch3_gdx_for/scratch-link-device-adapter.js
Labels: pr - needs review

#1907 Add blocks to GDX-FOR extension
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1912 Populate executable targets when runtime.targets is populated
  src/blocks/scratch3_control.js
  src/engine/runtime.js
  src/engine/target.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/sprites/rendered-target.js
  src/virtual-machine.js
  test/integration/hat-threads-run-every-frame.js
  test/unit/blocks_event.js
  test/unit/blocks_looks.js
  test/unit/engine_target.js
  test/unit/serialization_sb3.js
Labels: pr - needs review

#1920 Properly disconnect BLE socket in GDX-FOR scan/disconnect
  src/extensions/scratch3_gdx_for/index.js
  src/extensions/scratch3_gdx_for/scratch-link-device-adapter.js
Labels: pr - good to merge

#1916 Prevent excess event emitting in Vernier extension
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1839 fix: initialize stack frame params for all procedures
  src/blocks/scratch3_procedures.js
  src/engine/block-utility.js
  src/engine/thread.js
  test/fixtures/execute/procedures-nested-missing-no-param.sb2
  test/unit/engine_thread.js
Labels: pr - good to merge

#1924 Removing withResponse flag in GDX-FOR extension write method
  src/extensions/scratch3_gdx_for/scratch-link-device-adapter.js
Labels: pr - needs review

#1763 Various fixes to extension disconnect errors
  src/engine/runtime.js
  src/extensions/scratch3_ev3/index.js
  src/extensions/scratch3_microbit/index.js
  src/extensions/scratch3_wedo2/index.js
  src/io/ble.js
  src/io/bt.js
  src/virtual-machine.js
Labels: pr - good to merge

#1914 Prevent console errors when disconnecting/reconnect to Vernier extension
  src/extensions/scratch3_gdx_for/index.js
Labels: pr - good to merge

#1928 Improve the performance of the timer utilitiy
  src/engine/block-utility.js
Labels: performance, pr - good to merge

#1937 Localize Makey Makey extension blocks
  src/extensions/scratch3_makeymakey/index.js
Labels: pr - good to merge

#1938 Fix Text to Speech extension default input localization
  src/extensions/scratch3_text2speech/index.js
Labels: pr - good to merge

#1946 Fix saving and loading of slider min max values.
  src/serialization/sb3.js
  test/integration/monitors_sb2_to_sb3.js
Labels: pr - good to merge

#1941 Add reference for `runtime` to blocks container
  src/engine/blocks.js
  src/engine/runtime.js
  src/engine/target.js
  src/serialization/sb2.js
  src/serialization/sb3.js
  src/sprites/sprite.js
  src/virtual-machine.js
  test/integration/sb3-roundtrip.js
  test/integration/stack-click.js
  test/unit/blocks_event.js
  test/unit/blocks_sensing.js
  test/unit/engine_blocks.js
  test/unit/engine_sequencer.js
  test/unit/engine_target.js
  test/unit/engine_thread.js
  test/unit/io_cloud.js
  test/unit/sprites_rendered-target.js
  test/unit/virtual-machine.js
Labels: pr - needs review
