Repository scratchfoundation/scratch-vm, pull requests merged in 2019-10, with the labels that each got.

#2196 add Profiler.increment and Profiler.frame
  src/engine/execute.js
  src/engine/profiler.js
  src/engine/sequencer.js
  src/playground/benchmark.js
Labels: ergonomics, performance, pr - good to merge

#2292 Use bitmap skin for video preview
  src/io/video.js
Labels: pr - needs review

#2293 Fix video sensing error with stale matrices
  src/extensions/scratch3_video_sensing/library.js
  test/unit/extension_video_sensing.js
Labels: pr - needs review

#2286 Fix mod operator comment
  src/blocks/scratch3_operators.js
Labels: pr - good to merge

#2280 Inline Images in Extensions
  docs/extensions.md
  src/blocks/scratch3_core_example.js
  src/engine/runtime.js
  src/extension-support/argument-type.js
  test/integration/internal-extension.js
  test/unit/extension_conversion.js
Labels: pr - good to merge
