Repository scratchfoundation/scratch-vm, pull requests merged in 2020-03, with the labels that each got.

#2187 Consistently format text bubbles
  src/blocks/scratch3_looks.js
  test/unit/blocks_looks.js
Labels: pr - needs review

#2322 Use correct name in changeBlock in renameVariable
  src/engine/target.js
Labels: pr - good to merge

#2325 Fix old/incorrect list monitor names during deserialization
  src/serialization/sb3.js
  test/fixtures/list-monitor-rename.sb3
  test/integration/list-monitor-rename.js
Labels: pr - good to merge

#2333 Dont fix small values
  package-lock.json
  src/blocks/scratch3_looks.js
Labels: blocker, pr - needs review

#2336 Revert reformat think and ask bubbles
  src/blocks/scratch3_looks.js
  test/unit/blocks_looks.js
Labels: pr - needs review
