Repository scratchfoundation/scratch-vm, pull requests merged in 2020-05, with the labels that each got.

#2400 Remove BlockCached._shadowOps
  src/engine/execute.js
Labels: blocked, pr - good to merge

#2415 Remove RenderedTarget.setSay + its test
  src/sprites/rendered-target.js
  test/unit/sprites_rendered-target.js
Labels: pr - needs review

#2011 Give all backdrops a more equal chance of being randomly picked
  src/blocks/scratch3_looks.js
  src/util/math-util.js
  test/unit/util_math.js
Labels: pr - good to merge

#2425 Update sensing_of fields if variable gets renamed
  src/engine/blocks.js
  src/engine/target.js
  test/unit/engine_blocks.js
Labels: pr - good to merge

#2335 WeDo 2.0 isTilted-any function bug fix
  src/extensions/scratch3_wedo2/index.js
Labels: pr - good to merge
